AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Zunming Tea Backend - Serverless API

# ⚠️ IMPORTANT: All resources are prefixed with 'zmt-' to avoid conflicts with existing AWS resources
# This stack is completely isolated and won't affect other services in your AWS account

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    MemorySize: 512
    Environment:
      Variables:
        REGION: !Ref AWS::Region
        PAGES_TABLE: !Ref PagesTable
        PRODUCTS_TABLE: !Ref ProductsTable
        NAVIGATION_TABLE: !Ref NavigationTable
        SETTINGS_TABLE: !Ref SettingsTable
        UPDATES_TABLE: !Ref UpdatesTable
        GITHUB_PAT: !Ref GitHubPAT
        GITHUB_REPO: 'Ethanlita/zmt'
        MEDIA_BUCKET: !Ref MediaBucket
        MEDIA_CDN_URL: !Sub 'https://${MediaCdnDomain}'
    Architectures:
      - x86_64
    # Add tags for resource identification and cost tracking
    Tags:
      Project: ZunmingTea
      Environment: Production
      ManagedBy: SAM

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for authorization
    Default: 'arn:aws:cognito-idp:us-east-1:296821242554:userpool/us-east-1_T7MyJyPr0'
  
  GitHubPAT:
    Type: String
    Description: GitHub Personal Access Token for triggering workflows
    NoEcho: true
    Default: ''

  MediaCdnDomain:
    Type: String
    Description: Custom domain (CNAME) for the media CDN (e.g., s3.zunmingtea.com)
    Default: s3.zunmingtea.com

  MediaCertificateArn:
    Type: String
    Description: ACM certificate ARN (in us-east-1) for the media CloudFront distribution

Conditions:
  HasCognitoUserPool: !Not [!Equals [!Ref CognitoUserPoolArn, '']]

Resources:
  # API Gateway (isolated with unique name)
  ZmtApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: zmt-api-prod  # Unique name to avoid conflicts
      StageName: prod
      Tags:
        Project: ZunmingTea
        Environment: Production
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://admin.zunmingtea.com'"
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !If [HasCognitoUserPool, !Ref CognitoUserPoolArn, !Ref AWS::NoValue]
            AuthType: COGNITO_USER_POOLS
        AddDefaultAuthorizerToCorsPreflight: false
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: "/*"
          HttpMethod: "*"
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'

  ApiGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${ZmtApi}/access"
      RetentionInDays: 14

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: '*'

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ApiGatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ZmtApi
      ResponseType: DEFAULT_4XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://admin.zunmingtea.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  ApiGatewayResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ZmtApi
      ResponseType: DEFAULT_5XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://admin.zunmingtea.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  # DynamoDB Tables (with unique names and deletion protection)
  PagesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain  # Prevent accidental deletion
    UpdateReplacePolicy: Retain
    Properties:
      TableName: zmt-pages-prod  # Unique name to avoid conflicts
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production
      AttributeDefinitions:
        - AttributeName: page_slug
          AttributeType: S
      KeySchema:
        - AttributeName: page_slug
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ProductsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain  # Prevent accidental deletion
    UpdateReplacePolicy: Retain
    Properties:
      TableName: zmt-products-prod  # Unique name to avoid conflicts
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  NavigationTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: zmt-navigation-prod
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production
      AttributeDefinitions:
        - AttributeName: nav_id
          AttributeType: S
      KeySchema:
        - AttributeName: nav_id
          KeyType: HASH

  SettingsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: zmt-settings-prod
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production
      AttributeDefinitions:
        - AttributeName: settings_id
          AttributeType: S
      KeySchema:
        - AttributeName: settings_id
          KeyType: HASH

  UpdatesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: zmt-updates-prod
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production
      AttributeDefinitions:
        - AttributeName: update_id
          AttributeType: S
        - AttributeName: channel
          AttributeType: S
      KeySchema:
        - AttributeName: update_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: channel-index
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: channel
              KeyType: HASH

  MediaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: zmt-media-prod
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, HEAD]
            AllowedOrigins:
              - https://admin.zunmingtea.com
              - http://localhost:3001
              - http://localhost:4173
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: ZunmingTea
        - Key: Environment
          Value: Production

  MediaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MediaBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub '${MediaBucket.Arn}/*'

  MediaDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: ZunmingTea media CDN
        HttpVersion: http2
        PriceClass: PriceClass_100
        Aliases:
          - !Ref MediaCdnDomain
        Origins:
          - Id: MediaBucketOrigin
            DomainName: !GetAtt MediaBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: MediaBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
        DefaultRootObject: ''
        ViewerCertificate:
          AcmCertificateArn: !Ref MediaCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  # Lambda Functions
  ContentHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zmt-content-handler-prod  # Unique name to avoid conflicts
      CodeUri: .
      Handler: src/handlers/content.handler
      Description: Handle content CRUD operations for Zunming Tea
      Tags:
        Project: ZunmingTea
        Environment: Production
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref NavigationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UpdatesTable
      Events:
        # Public endpoints (no auth)
        GetContentByType:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/{type}
            Method: GET
            Auth:
              Authorizer: NONE
        GetContentIds:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/{type}/ids
            Method: GET
            Auth:
              Authorizer: NONE
        GetContentById:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/{type}/{id}
            Method: GET
            Auth:
              Authorizer: NONE
        GetPublicPages:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /public/pages
            Method: GET
            Auth:
              Authorizer: NONE
        GetPublicPageById:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /public/pages/{id}
            Method: GET
            Auth:
              Authorizer: NONE
        GetPublicUpdates:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /public/updates
            Method: GET
            Auth:
              Authorizer: NONE
        GetPublicUpdateById:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /public/updates/{id}
            Method: GET
            Auth:
              Authorizer: NONE
        GetUpdateChannels:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/updates/channels
            Method: GET
            Auth:
              Authorizer: NONE
        # Protected endpoints (require Cognito auth)
        CreateOrUpdateContent:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/{type}/{id}
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        DeleteContent:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /content/{type}/{id}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  NavigationHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zmt-navigation-handler-prod
      CodeUri: .
      Handler: src/handlers/navigation.handler
      Description: Manage site navigation tree and settings
      Tags:
        Project: ZunmingTea
        Environment: Production
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NavigationTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SettingsTable
      Events:
        GetNavigation:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /navigation
            Method: GET
            Auth:
              Authorizer: NONE
        UpdateNavigation:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /navigation
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        GetSettingsPublic:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /settings/public
            Method: GET
            Auth:
              Authorizer: NONE
        GetSettings:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /settings
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateFooter:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /settings/footer
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  ServicesHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zmt-services-handler-prod  # Unique name to avoid conflicts
      CodeUri: .
      Handler: src/handlers/services.handler
      Description: Handle translation and publish services for Zunming Tea
      Tags:
        Project: ZunmingTea
        Environment: Production
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - translate:TranslateText
              Resource: '*'
      Events:
        Translate:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /translate
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer
        Publish:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /publish
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  MediaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zmt-media-handler-prod
      CodeUri: .
      Handler: src/handlers/media.handler
      Description: Generate pre-signed URLs for CMS asset uploads
      Tags:
        Project: ZunmingTea
        Environment: Production
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub '${MediaBucket.Arn}/*'
      Events:
        CreateUploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref ZmtApi
            Path: /media/upload
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  ApiId:
    Description: API Gateway ID
    Value: !Ref ZmtApi
    Export:
      Name: ZmtApiId

  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ZmtApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: ZmtApiUrl

  PagesTableName:
    Description: DynamoDB Pages table name
    Value: !Ref PagesTable
    Export:
      Name: ZmtPagesTable

  ProductsTableName:
    Description: DynamoDB Products table name
    Value: !Ref ProductsTable
    Export:
      Name: ZmtProductsTable

  MediaBucketName:
    Description: S3 bucket for CMS media uploads
    Value: !Ref MediaBucket
    Export:
      Name: ZmtMediaBucket

  MediaCdnDomainOutput:
    Description: CloudFront alias serving media files
    Value: !Ref MediaCdnDomain

  MediaCdnUrl:
    Description: Public base URL for uploaded media
    Value: !Sub 'https://${MediaCdnDomain}'
